version: '3'

volumes:
  postgres_volume:

services:
  app:
    container_name: app
    build:
      context: .
    ports:
      - "50052:50051"
    entrypoint: ["/root/entrypoint.sh"]
    profiles:
      - server
  postgres:
    container_name: postgres
    image: postgres:15.4
    environment:
      - "POSTGRES_DB=${PG_DATABASE_NAME}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "${PG_PORT}:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    profiles:
      - server
      - local